/**
 * Maps the infographic brief comments in the markdown content to image files.
 *
 * A brief is an HTML comment block whose first line is an uppercase label, for example
 * `<!-- ANSOFF MATRIX - Place after ... -->`. If its label matches an entry here, the
 * rehype plugin renders the image. Images are generated by scripts/build-infographics.mjs
 * into public/infographics/, apart from the older hand-made SVGs in public/.
 */

const IG = '/infographics';

/** Unit pages that have their own badge row (unit number -> file). */
const BADGE_UNITS = new Set(['501', '506', '509', '701', '702', '704', '705', '706']);

/** Key command verb per unit, which decides the highlighted ladder image. */
const LADDER_VERB = {
  501: 'evaluate',
  506: 'evaluate',
  509: 'evaluate',
  701: 'critically-analyse',
  702: 'critically-analyse',
  704: 'critically-analyse',
  705: 'critically-analyse',
  706: 'critically-analyse',
};

/** The unit number in a page id such as `cmi-level-5-unit-501`, or null. */
const unitNumber = (pageId) => pageId.match(/unit-(\d{3})$/)?.[1] ?? null;

/** [label test, image path or (pageId) => image path | null] */
const ENTRIES = [
  [/^PROCESS INFOGRAPHIC/, `${IG}/process-home-5-steps.svg`],
  [/^PROCESS TIMELINE/, `${IG}/process-writing-service-5-steps.svg`],
  [/^ONLINE SERVICE PROCESS/, `${IG}/process-online-6-steps.svg`],
  [/^LEVEL SELECTOR/, `${IG}/level-selector.svg`],
  [/^LEVEL COMPARISON INFOGRAPHIC/, `${IG}/level-5-vs-7-hub.svg`],
  [/^LEVEL COMPARISON TABLE/, `${IG}/levels-comparison-table.svg`],
  [/^CMI LEVELS ON THE RQF/, `${IG}/rqf-levels-ladder.svg`],
  [/^AWARD VS CERTIFICATE VS DIPLOMA/, `${IG}/award-certificate-diploma.svg`],
  [/^LEVEL ([3-6]) QUALIFICATION STRUCTURE/, (_page, m) => `${IG}/qualification-structure-level-${m[1]}.svg`],
  [/^CMI QUALIFICATION JOURNEY/, `${IG}/qualification-journey.svg`],
  [/^PRICING TIERS/, `${IG}/pricing-tiers.svg`],
  [/^CMI GRADE STANDARD COMPARISON/, `${IG}/grade-standard-comparison.svg`],
  [/^TUTORING SERVICE FORMATS/, `${IG}/tutoring-formats.svg`],
  [/^CMI GRADING SYSTEM/, `${IG}/resubmission-grading-system.svg`],
  [/^FIVE MOST COMMON RESUBMISSION TRIGGERS/, `${IG}/resubmission-triggers.svg`],
  [/^RESUBMISSION CHECKLIST/, `${IG}/resubmission-checklist.svg`],
  [/^SUBMISSION-READY CHECKLIST/, `${IG}/submission-ready-checklist.svg`],
  [/^COMMAND VERB GRADE BAND TABLE/, '/cmi-command-verb-grades.svg'],
  [/^CMI REPORT STRUCTURE DIAGRAM/, '/cmi-management-report-structure.svg'],
  // The ladder with the unit's key verb highlighted. Units not listed fall back to the plain ladder.
  [
    /^(CMI )?COMMAND VERB LADDER/,
    (page) => {
      const verb = LADDER_VERB[unitNumber(page)];
      return verb ? `${IG}/cmi-command-verb-ladder-${verb}.svg` : '/cmi-command-verb-ladder.svg';
    },
  ],
  [/^UNIT INFO BADGE ROW/, (page) => (BADGE_UNITS.has(unitNumber(page)) ? `${IG}/unit-badges-${unitNumber(page)}.svg` : null)],
  [/^LEADERSHIP THEORIES COMPARISON/, `${IG}/unit-501-leadership-theories.svg`],
  [/^BUDGET TYPES COMPARISON/, `${IG}/unit-506-budget-types.svg`],
  [/^VARIANCE ANALYSIS EXPLAINER/, `${IG}/unit-506-variance-analysis.svg`],
  [/^MENDELOW/, `${IG}/unit-509-mendelow-matrix.svg`],
  [/^STAKEHOLDER COMMUNICATION STRATEGY/, `${IG}/unit-509-communication-table.svg`],
  [/^STRATEGIC LEADERSHIP MODELS COMPARISON/, `${IG}/unit-701-leadership-models.svg`],
  [/^CRITICALLY ANALYSE VS EVALUATE/, `${IG}/unit-701-critically-analyse-vs-evaluate.svg`],
  [/^9-BOX GRID/, `${IG}/unit-702-9-box-grid.svg`],
  [/^HPWS PRACTICE BUNDLES/, `${IG}/unit-702-hpws-bundles.svg`],
  [/^ANSOFF MATRIX/, `${IG}/unit-704-ansoff-matrix.svg`],
  [/^PORTER'S FIVE FORCES/, `${IG}/unit-704-porters-five-forces.svg`],
  [/^KOTTER'S 8-STEP/, `${IG}/unit-705-kotter-critique.svg`],
  [/^CHANGE MANAGEMENT FRAMEWORKS COMPARISON/, `${IG}/unit-705-change-frameworks.svg`],
  [/^ETHICAL THEORIES COMPARISON/, `${IG}/unit-706-ethical-theories.svg`],
  [/^SCHEIN CULTURE MODEL APPLIED TO ETHICS/, `${IG}/unit-706-schein-ethics.svg`],
];

/** Older briefs that predate this map. They render as a placeholder unless a file is mapped below. */
const LEGACY_LABELS =
  /^(TRUST BADGE|CMI COMMAND VERB|CMI MANAGEMENT REPORT|GIBBS REFLECTIVE|CMI LEVEL 5 VS|STUDENT PROFILE|NHS BAND TO CMI|CMI UNITS RELEVANT TO NHS)/i;

/** True if the first line of a comment block is an infographic brief. */
export function isInfographicLabel(text) {
  return LEGACY_LABELS.test(text) || ENTRIES.some(([test]) => test.test(text.toUpperCase()));
}

/** Public path of the image for a brief, or null if none exists (the plugin then renders a placeholder). */
export function infographicImageSrc(label, pageId = '') {
  const u = label.toUpperCase();
  for (const [test, target] of ENTRIES) {
    const m = u.match(test);
    if (m) return typeof target === 'function' ? target(pageId, m) : target;
  }
  if (u.startsWith('TRUST BADGE')) return '/trust-badge.png';
  if (u.startsWith('CMI COMMAND VERB COGNITIVE')) return '/cmi-command-verb-ladder.svg';
  if (u.startsWith('CMI COMMAND VERB') || u.includes('GRADE BAND')) return '/cmi-command-verb-grades.svg';
  if (u.startsWith('CMI MANAGEMENT REPORT')) return '/cmi-management-report-structure.svg';
  if (u.startsWith('GIBBS REFLECTIVE')) return '/cmi-gibbs-reflective-cycle.svg';
  return null;
}
